Repository gajus/eslint-plugin-jsdoc, pull requests merged in 2019-07, with the labels that each got.

#307 no-undefined-types: Handle GCC generic functions
  README.md
  src/rules/noUndefinedTypes.js
  test/rules/assertions/noUndefinedTypes.js
Labels: enhancement

#302 Allow rejecting normally valid tag names and/or providing custom error messages when suggesting tags to reject or replace
  .README/README.md
  README.md
  package.json
  src/iterateJsdoc.js
  src/rules/checkExamples.js
  src/rules/checkParamNames.js
  src/rules/checkTagNames.js
  src/rules/requireDescription.js
  src/rules/requireHyphenBeforeParamDescription.js
  src/rules/requireParam.js
  src/rules/requireParamDescription.js
  src/rules/requireParamName.js
  src/rules/requireParamType.js
  src/rules/requireReturns.js
  src/rules/requireReturnsCheck.js
  src/rules/requireReturnsDescription.js
  src/rules/requireReturnsType.js
  test/rules/assertions/checkParamNames.js
  test/rules/assertions/checkTagNames.js
  test/rules/assertions/requireDescription.js
  test/rules/assertions/requireHyphenBeforeParamDescription.js
  test/rules/assertions/requireParam.js
  test/rules/assertions/requireParamDescription.js
  test/rules/assertions/requireParamName.js
  test/rules/assertions/requireParamType.js
  test/rules/assertions/requireReturns.js
  test/rules/assertions/requireReturnsCheck.js
  test/rules/assertions/requireReturnsDescription.js
  test/rules/assertions/requireReturnsType.js
Labels: enhancement

#313 `match-description`
  .README/rules/match-description.md
  README.md
  src/rules/matchDescription.js
  test/rules/assertions/matchDescription.js
Labels: enhancement

#320 Allow `match-description` to apply to descriptions of arbitrary tags
  .README/rules/match-description.md
  README.md
  src/rules/matchDescription.js
  test/rules/assertions/matchDescription.js
Labels: bug, enhancement

#322 feat(`check-examples`): apply to all contexts
  .README/rules/check-examples.md
  README.md
  src/rules/checkExamples.js
  test/rules/assertions/checkExamples.js
Labels: enhancement

#321 `require-example`: add `contexts` option
  .README/rules/require-example.md
  README.md
  src/rules/requireExample.js
  test/rules/assertions/requireExample.js
Labels: enhancement

#335 Indent
  .README/rules/check-examples.md
  package.json
  src/iterateJsdoc.js
  src/rules/checkExamples.js
  test/rules/assertions/checkExamples.js
Labels: bug, enhancement

#338 `require-description-complete-sentence`: limit checking by default to likely tags and new option array
  .README/rules/require-description-complete-sentence.md
  README.md
  src/jsdocUtils.js
  src/rules/requireDescriptionCompleteSentence.js
  test/rules/assertions/requireDescriptionCompleteSentence.js
Labels: bug, enhancement

#339 Tag name preference
  README.md
  src/iterateJsdoc.js
  src/rules/checkParamNames.js
  src/rules/checkTagNames.js
  src/rules/matchDescription.js
  src/rules/requireDescription.js
  src/rules/requireDescriptionCompleteSentence.js
  src/rules/requireParam.js
  src/rules/requireReturns.js
  src/rules/requireReturnsCheck.js
  test/rules/assertions/implementsOnClasses.js
  test/rules/assertions/matchDescription.js
  test/rules/assertions/requireDescription.js
  test/rules/assertions/requireDescriptionCompleteSentence.js
Labels: bug

#241 build: make create-readme part of test
  .travis.yml
  package.json
  src/bin/generateReadme.js
Labels: enhancement

#361 Add `symbol` and `bigint` to native types
  .README/rules/check-types.md
  README.md
  src/rules/checkTypes.js
Labels: enhancement
