Repository gajus/eslint-plugin-jsdoc, pull requests merged in 2020-05, with the labels that each got.

#532 `checkDestructured` property to disable destructured checks
  src/rules/requireParam.js
  test/rules/assertions/requireParam.js
Labels: enhancement

#544 More accurate Configuration section
  README.md
Labels: documentation

#548 `require-description-complete-sentence`: `newlineBeforeCapsAssumesBadSentenceEnd` option
  README.md
  src/rules/requireDescriptionCompleteSentence.js
  test/rules/assertions/requireDescriptionCompleteSentence.js
Labels: enhancement

#556 refactor: remove `warnRemovedSettings`
  README.md
  src/WarnSettings.js
  src/rules/checkExamples.js
  src/rules/requireExample.js
  src/rules/requireJsdoc.js
  src/rules/requireReturns.js
  src/rules/validTypes.js
  src/warnRemovedSettings.js
  test/rules/assertions/checkExamples.js
  test/rules/assertions/requireExample.js
  test/rules/assertions/requireJsdoc.js
  test/rules/assertions/requireReturns.js
  test/rules/assertions/validTypes.js
  test/warnRemovedSettings.js
Labels: refactor
